<?php

require_once dirname(__FILE__) . '/../../../prods/src/ProdsRule.class.php';

/**
 * Test class for ProdsRule.
 * Generated by PHPUnit on 2011-02-24 at 16:39:16.
 */
class ProdsRuleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ProdsRule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
