<?php

require_once dirname(__FILE__) . '/../../../prods/src/RODSConnManager.class.php';

/**
 * Test class for RODSConnManager.
 * Generated by PHPUnit on 2011-02-24 at 16:39:16.
 */
class RODSConnManagerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RODSConnManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RODSConnManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetConn().
     */
    public function testGetConn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testReleaseConn().
     */
    public function testReleaseConn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
