<?php

require_once dirname(__FILE__) . '/../../../prods/src/RODSGenQueResults.class.php';

/**
 * Test class for RODSGenQueResults.
 * Generated by PHPUnit on 2011-02-24 at 16:39:14.
 */
class RODSGenQueResultsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RODSGenQueResults
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RODSGenQueResults;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testAddResults().
     */
    public function testAddResults() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetValues().
     */
    public function testGetValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTotalCount().
     */
    public function testGetTotalCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetNumCol().
     */
    public function testGetNumCol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetNumRow().
     */
    public function testGetNumRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
