<?php

require_once dirname(__FILE__) . '/../../../prods/src/RODSGenQueConds.class.php';

/**
 * Test class for RODSGenQueConds.
 * Generated by PHPUnit on 2011-02-24 at 16:39:12.
 */
class RODSGenQueCondsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RODSGenQueConds
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RODSGenQueConds;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testAdd().
     */
    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPacketize().
     */
    public function testPacketize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPacketizeKW().
     */
    public function testPacketizeKW() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
